import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import SwitchMode from "./SwitchMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Ui",
  description: "Generated by create next app",
};

export default function RootLayout({children}){
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <SwitchMode/>
          {children}
        </Provider>
        </body>
    </html>
  );
}
